- name: check if host already registered
  command: subscription-manager status
  register: subs_result
  failed_when: false
  changed_when: "'Current' in subs_result.stderr"

- name: Unregister hosts
  command: subscription-manager unregister
  retries: 5
  delay: 5
  when: subs_result.changed

