- name: Check if instance exists
  shell:  openstack server show {{ instance_name }}
  register: instance_output
  ignore_errors: true

- name: Create OpenStack Instance
  shell: openstack server create --flavor {{ instance_flavor }} --image "{{ instance_image }}" --network {{ instance_network }} --key-name {{ instance_ssh_key_name }} --security-group {{ instance_security_group }} {{ instance_name }} --wait
  when: instance_output.rc != 0
