- name: check if host already registered
  command: subscription-manager list --available --match-installed --pool-only
  register: subs_result
  failed_when: false
  changed_when: "'This system is not yet registered' in subs_result.stderr"

- name: Unregister hosts
  command: subscription-manager unregister
  retries: 5
  delay: 5
  when: subs_result.changed

