- name: Deploy a StatefulSet on OpenShift
  hosts: localhost
  gather_facts: false
  run_once: true

  tasks:
  - import_role:
      name: ocp-stateful-set
    vars:
      openshift_cli: "oc"
      project_name: "rocket"
      project_display_name: "Rocket-Chat"
      project_desc: "A Showcase for StatefulSets on OpenShift"
      # application_url: ""
      rocket_memory_limit: "512Mi"
      mongodb_service_name: "mongodb"
      mongodb_internal_service_name: "mongodb-internal"
      mongodb_database: "mongodb"
      mongodb_user: "mongodb_user"
      mongodb_password: "redhat"
      mongodb_admin_password: "redhat"
      mongodb_replica_name: "rs0"
      mongodb_keyfile_value: "12345678901234567890"
      mongodb_replicas: "3"
      mongodb_memory_limit: "256Mi"
