- name: Check if network exists
  shell: openstack show network {{ project }}
  ignore_errors: yes
  register: openstack_network_show

- name: Create OpenStack Project Network
  shell: openstack network create {{ project }}
  register: openstack_network_create
  when: openstack_network_show.rc != 0

- name: Create OpenStack Project Subnet
  shell: openstack subnet create --network {{ project }} --allocation-pool start={{ start_range }},end={{ end_range }} --dns-nameserver 213.133.98.98 --subnet-range {{ cidr }} {{ project }}_subnet
  when: openstack_network_create.rc == 0

- name: Create Keypair File
  file:
    path: /tmp/{{ project }}.pem
    state: touch

 - name: Add Private Key to File
  blockinfile:
    block: "{{ private_key }}"
    dest: "/tmp/{{ project }}.pem"
  when: openstack_network_create.rc == 0

- name: Set permissions on keypair file
  file:
    path: /tmp/{{ project }}.pem
    mode: 0400

- name: Create OpenStack Keypair
  shell: openstack keypair create --private-key /tmp/{{ project }}.pem {{ project }}
  become: yes
  register: create_keypair_file
  when: openstack_network_create.rc == 0

#- name: Cleanup private key file
#  shell: rm -f /root/{{ project }}.pem
#  when: create_keypair_file.rc == 0

- name: Create Security Group Base
  shell: openstack security group create base --description "Allow base ports"
  register: security_group_create
  when: openstack_network_create.rc == 0

- name: Allow 22 Ingress to Base Group
  shell: openstack security group rule create --protocol TCP --dst-port 22 --remote-ip 0.0.0.0/0 base
  when: security_group_create.rc == 0

- name: Allow 80 Ingress to Base Group
  shell: openstack security group rule create --protocol TCP --dst-port 80 --remote-ip 0.0.0.0/0 base
  when: security_group_create.rc == 0

- name: Allow 443 Ingress to Base Group
  shell: openstack security group rule create --protocol TCP --dst-port 443 --remote-ip 0.0.0.0/0 base
  when: security_group_create.rc == 0

- name: Allow ICMP Ingress to Base Group
  shell: openstack security group rule create --protocol ICMP --remote-ip 0.0.0.0/0 base
  when: security_group_create.rc == 0
